### ISSUE TITLE
publish a new version?

### ISSUE THREAD

**Issue by peter-mouland** [kpdecker/node-resemble#13]
I see a PR (https://github.com/kpdecker/node-resemble/pull/12) has gone in which has not yet been published.

I understand the PR is no longer maintained, but a new version would be gratefully received!

I see there was an offer to help with maintenance, did that go anywhere?  Would it be helpful to have multiple maintainers? I'd be happy to put my name into the hat also.

**Comment by kpdecker** [comment]
Honestly can't remember. @snollygolly has contributor access to the repository now, but that's all that I remember.
