### ISSUE TITLE
Support native Resemble's largeImageThreshold option

### ISSUE THREAD

**Issue by topherhunt** [kpdecker/node-resemble#4]
Hey there - thanks for making such a great port. I've had various issues with other ResembleJS -> Node ports and settled on this package, but one issue comes up: my use case requires diff files with no visual artifacts so I rely on the `largeImageThreshold` setting (or rather, I rely on my ability to disable it). From looking through the source, it looks like you've removed `largeImageThreshold` in order to simplify the logic around the `skip` variable. How hard would it be to add this setting back in? I can manually change the package code in the meantime, but would rather not rely on that long-term, and suspect other users may be in the same boat.

Thanks in advance!

**Comment by kpdecker** [comment]
I honestly can't remember as I ported this code quite awhile ago. If you
are hacking on the package, I'd be glad to look at any pull requests that
you create so we can merge the code into one source.
